publishDir = 'docs'
baseURL = 'https://muskanshaikh07-git.github.io/my-blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
sectionPagesMenu = "main"

[params]
  recent_posts_number = 5
